//
//  WeView2DemoConstants.h
//  WeViews2DemoApp
//
//  Copyright (c) 2013 Charles Matthew Chen. All rights reserved.
//

#pragma once

#define NOTIFICATION_LAYOUT_UPDATED @"NOTIFICATION_LAYOUT_UPDATED"
#define NOTIFICATION_SELECTION_CHANGED @"NOTIFICATION_SELECTION_CHANGED"
#define NOTIFICATION_ITEM_ADDED @"NOTIFICATION_ITEM_ADDED"
#define NOTIFICATION_SELECTION_ALTERED @"NOTIFICATION_SELECTION_ALTERED"
