//
//  WeViewDemoConstants.h
//  WeView 2
//
//  Copyright (c) 2013 Charles Matthew Chen. All rights reserved.
//
//  Distributed under the Apache License v2.0.
//  http://www.apache.org/licenses/LICENSE-2.0.html
//

#pragma once

#define NOTIFICATION_LAYOUT_UPDATED @"NOTIFICATION_LAYOUT_UPDATED"
#define NOTIFICATION_DEMO_CHANGED @"NOTIFICATION_DEMO_CHANGED"
#define NOTIFICATION_SELECTION_CHANGED @"NOTIFICATION_SELECTION_CHANGED"
#define NOTIFICATION_ITEM_ADDED @"NOTIFICATION_ITEM_ADDED"
#define NOTIFICATION_SELECTION_ALTERED @"NOTIFICATION_SELECTION_ALTERED"
#define NOTIFICATION_SET_SELECTION_TO @"NOTIFICATION_SET_SELECTION_TO"

#define TUTORIAL
